name: Feature Request
title: "[Feature Request]: "
description: Request or propose a new feature
labels:
  - feature
projects: ["201st-Noah/3"]
body:
  - type: dropdown
    id: type
    attributes:
      label: Feature type
      description: What feature would you like to see in the RitualMagic mod? Please
        select one or multiple options from the dropdown list below.
      options:
        - Weapon
        - Tool
        - Armor
        - Ability
        - World generation
        - Game mechanics
        - Other
  - type: textarea
    id: description
    attributes:
      label: Feature description
      description: Please enter a precise decision of the feature. Do not be afraid of
        writing to much :)
      value: I would like to see a sword that does 1,000,000 damage.
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Have you considered other alternatives? Does your requested feature
        have similarities to other games? If so, please provide some enough
        resources such as links and images so we have a better understanding of
        your feature.
      value: |-
        Yes, I did.
        Check out the sword "Either Morgan" from the mod "Mahou Tsukai". 
        https://www.youtube.com/watch?v=dQw4w9WgXcQ
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Some checkboxes
      options:
        - label: I want to work on this feature
        - label: I am open for a discussion on GitHub
  - type: markdown
    attributes:
      value: |-
        Thank you for your feature request! We will review it and get back to you as soon as possible.
        If you have any questions, feel free to ask in the discussion section of this issue.
