package be.noah.ritual_magic.datagen;

import be.noah.ritual_magic.RitualMagic;
import be.noah.ritual_magic.item.ModItems;
import net.minecraft.data.PackOutput;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.Item;
import net.minecraftforge.client.model.generators.ItemModelBuilder;
import net.minecraftforge.client.model.generators.ItemModelProvider;
import net.minecraftforge.common.data.ExistingFileHelper;
import net.minecraftforge.registries.RegistryObject;

public class ModItemModelProvider extends ItemModelProvider {
    public ModItemModelProvider(PackOutput output, ExistingFileHelper existingFileHelper) {
        super(output, RitualMagic.MODID, existingFileHelper);
    }

    @Override
    protected void registerModels() {
        simpleItem(ModItems.DRAGON_PLATE);
        simpleItem(ModItems.DRAGON_SCALE);
        simpleItem(ModItems.ATLANTIAN_SCRAP);
        simpleItem(ModItems.ATLANTIAN_STEEL_INGOT);
        simpleItem(ModItems.DWARVEN_SCRAP);
        simpleItem(ModItems.DWARVEN_STEEL_INGOT);
        simpleItem(ModItems.WARDEN_CORE);
        simpleItem(ModItems.DWARVEN_TEMPLATE);
        simpleItem(ModItems.TORCH);
        simpleItem(ModItems.BUILDERSTAFF);
        simpleItem(ModItems.ICE_SHARD);

        // custom models (located in resources/assets/ritual_magic/models/item) that are not generated by `runData`
        // - ritual_magic:item/speer
        // - ritual_magic:item/dwarven_axe
        // - ritual_magic:item/nether_scepter
    }
    private ItemModelBuilder simpleItem(RegistryObject<Item> item) {
        return withExistingParent(item.getId().getPath(),
                new ResourceLocation("item/generated")).texture("layer0",
                new ResourceLocation(RitualMagic.MODID,"item/" + item.getId().getPath()));
    }
}
